"""empty message

Revision ID: 01f7cf0d7c5b
Revises: 12b0706c4052
Create Date: 2019-11-14 08:48:19.741996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f7cf0d7c5b'
down_revision = '12b0706c4052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technology', 'url',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=240),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technology', 'url',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
