"""empty message

Revision ID: 12b0706c4052
Revises: e4a1a46a45bc
Create Date: 2019-11-14 08:32:12.205503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b0706c4052'
down_revision = 'e4a1a46a45bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technology', sa.Column('sdk_api', sa.Boolean(), nullable=True))
    op.add_column('technology', sa.Column('short_description', sa.Text(), nullable=True))
    op.drop_column('technology', 'sdk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technology', sa.Column('sdk', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('technology', 'short_description')
    op.drop_column('technology', 'sdk_api')
    # ### end Alembic commands ###
