"""empty message

Revision ID: db3a782f2acc
Revises: 
Create Date: 2019-11-28 14:04:03.292140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3a782f2acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('modality', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=240), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('passive', sa.Boolean(), nullable=True),
    sa.Column('portable', sa.Boolean(), nullable=True),
    sa.Column('wearing_position', sa.String(length=80), nullable=True),
    sa.Column('open_source', sa.Boolean(), nullable=True),
    sa.Column('sdk_api', sa.Boolean(), nullable=True),
    sa.Column('raw_data_access', sa.Boolean(), nullable=True),
    sa.Column('minimum_cost_gbp', sa.Float(), nullable=True),
    sa.Column('maximum_cost_gbp', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(length=80), nullable=True),
    sa.Column('clinical_validation', sa.String(length=80), nullable=True),
    sa.Column('medical_approval', sa.String(length=80), nullable=True),
    sa.Column('self_administer', sa.String(length=80), nullable=True),
    sa.Column('compatibility', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('technology')
    op.drop_table('modality')
    op.drop_table('measurable')
    # ### end Alembic commands ###
