"""empty message

Revision ID: e4a1a46a45bc
Revises: 46e2aaac7a65
Create Date: 2019-11-13 16:28:17.052421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a1a46a45bc'
down_revision = '46e2aaac7a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('passive', sa.Boolean(), nullable=True),
    sa.Column('portable', sa.Boolean(), nullable=True),
    sa.Column('wearing_position', sa.String(length=80), nullable=True),
    sa.Column('open_source', sa.Boolean(), nullable=True),
    sa.Column('sdk', sa.Boolean(), nullable=True),
    sa.Column('raw_data_access', sa.Boolean(), nullable=True),
    sa.Column('minimum_cost_gbp', sa.Float(), nullable=True),
    sa.Column('maximum_cost_gbp', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(length=80), nullable=True),
    sa.Column('clinical_validation', sa.String(length=80), nullable=True),
    sa.Column('medical_approval', sa.String(length=80), nullable=True),
    sa.Column('self_administer', sa.String(length=80), nullable=True),
    sa.Column('compatibility', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technology')
    # ### end Alembic commands ###
