"""empty message

Revision ID: f4887056e1a6
Revises: db3a782f2acc
Create Date: 2019-11-28 18:45:02.197239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4887056e1a6'
down_revision = 'db3a782f2acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('modality', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=240), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('passive', sa.Boolean(), nullable=True),
    sa.Column('portable', sa.Boolean(), nullable=True),
    sa.Column('wearing_position', sa.String(length=80), nullable=True),
    sa.Column('open_source', sa.Boolean(), nullable=True),
    sa.Column('sdk_api', sa.Boolean(), nullable=True),
    sa.Column('raw_data_access', sa.Boolean(), nullable=True),
    sa.Column('minimum_cost_gbp', sa.Float(), nullable=True),
    sa.Column('maximum_cost_gbp', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(length=80), nullable=True),
    sa.Column('clinical_validation', sa.String(length=80), nullable=True),
    sa.Column('medical_approval', sa.String(length=80), nullable=True),
    sa.Column('self_administer', sa.String(length=80), nullable=True),
    sa.Column('compatibility', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('modality')
    op.drop_table('technology')
    op.drop_table('measurable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurable',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modality', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='measurable_pkey')
    )
    op.create_table('technology',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=240), autoincrement=False, nullable=True),
    sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('passive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('portable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('wearing_position', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('open_source', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sdk_api', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('raw_data_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('minimum_cost_gbp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_cost_gbp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('availability', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('clinical_validation', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('medical_approval', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('self_administer', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('compatibility', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='technology_pkey')
    )
    op.create_table('modality',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='modality_pkey')
    )
    op.drop_table('technologies')
    op.drop_table('modalities')
    op.drop_table('measurables')
    # ### end Alembic commands ###
